# Generated by Django 5.2.7 on 2025-10-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_aluno', '0005_tbcarro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TbCarro',
        ),
    ]
