# Generated by Django 5.2.7 on 2025-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_aluno', '0003_remove_tbalunos_nome_mae_tbalunos_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbalunos',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
